#!/usr/bin/env bash
# modules/sheldon.sh — sheldon zsh plugin manager with curated plugin set
# Platform: all
# shellcheck disable=SC2034  # module interface vars are read by the installer when sourced
set -euo pipefail
IFS=$'\n\t'

MODULE_NAME="sheldon"
MODULE_DESC="sheldon plugin manager with curated plugin set"
MODULE_PLATFORM="all"

_SHELDON_PLUGINS=(
  "zsh-users/zsh-autosuggestions"
  "zsh-users/zsh-syntax-highlighting"
  "zsh-users/zsh-completions"
  "Aloxaf/fzf-tab"
  "mattmc3/zsh-safe-rm"
  "rupa/z"
  "zsh-users/zsh-history-substring-search"
)

# Installs sheldon + its curated plugin set and writes the zsh init block.
# plugins.toml is generated by `sheldon init` on first run; subsequent runs
# use `sheldon add` which is idempotent-ish (errors on duplicate, silenced).
install() {
  core::pkg_install sheldon

  local config="${HOME}/.config/sheldon/plugins.toml"
  if [[ ! -f "${config}" ]]; then
    sheldon init --shell zsh
  fi

  local plugin name
  for plugin in "${_SHELDON_PLUGINS[@]}"; do
    name="${plugin##*/}"
    # sheldon add errors on "plugin already present"; silence it, then move on.
    sheldon add "${name}" --github "${plugin}" >/dev/null 2>&1 || true
  done

  _sheldon::patch_fpath_for_zsh_completions "${config}"

  # Init block: sheldon source + compinit + history key bindings.
  # These three must run in this order: sheldon first populates fpath,
  # compinit then consumes it, and the history-substring bindkeys need
  # the plugin (loaded by sheldon source) to already be in memory.
  core::ensure_block "${HOME}/.zshrc" "sheldon" "$(
    cat <<'BLOCK'
eval "$(sheldon source)"

# Completion system (after sheldon so fpath is fully populated)
autoload -Uz compinit && compinit

# History substring search key bindings (plugin loaded above)
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
BLOCK
  )"
}

uninstall() {
  core::remove_block "${HOME}/.zshrc" "sheldon"
}

# Patches the zsh-completions plugin in sheldon's plugins.toml to use
# `apply = ["fpath"]` — the CLI has no direct flag for this. Without it,
# zsh-completions triggers "insecure directories" warnings and completion
# misfires. Idempotent: if the apply key is already present, no-op.
_sheldon::patch_fpath_for_zsh_completions() {
  local config="${1}"
  if awk '/^\[plugins\.zsh-completions\]/ { in_s=1; next } /^\[/ { in_s=0 } in_s && /^apply = \["fpath"\]/ { f=1 } END { exit !f }' "${config}"; then
    return 0
  fi
  local tmp
  tmp="$(mktemp)"
  awk '
    /^\[plugins\.zsh-completions\]/ {
      print
      print "apply = [\"fpath\"]"
      next
    }
    { print }
  ' "${config}" >"${tmp}"
  mv "${tmp}" "${config}"
  core::log INFO "Patched zsh-completions to use fpath in ${config}"
}
